module.exports = {
	CHANGE_STATUS: 'CHANGE_STATUS',
	CHANGE_SHARE: 'CHANGE_SHARE',
  POST: 'POST',
  NEW_TEMPLATE: 'NEW_TEMPLATE',
  CHANGE_COMMENT: 'CHANGE_COMMENT',
  POST_COMMENT: 'POST_COMMENT',
  CLEAR_COMMENT_TEMPLATE: 'CLEAR_COMMENT_TEMPLATE'
};