module.exports = {
	CHANGE_STATUS: 'CHANGE_STATUS',
  POST_STATUS: 'POST_STATUS',
  NEW_STATUS_TEMPLATE: 'NEW_STATUS_TEMPLATE',
  CHANGE_COMMENT: 'CHANGE_COMMENT',
  POST_COMMENT: 'POST_COMMENT',
  CLEAR_COMMENT_TEMPLATE: 'CLEAR_COMMENT_TEMPLATE'
};