module.exports = {
	CHANGE_RECIPIENT: 'CHANGE_RECIPIENT',
  CHANGE_SUBJECT: 'CHANGE_SUBJECT',
  CHANGE_MESSAGE: 'CHANGE_MESSAGE',
  SEND: 'SEND',
  NEW_TEMPLATE: 'NEW_TEMPLATE',
  SELECT_THREAD: 'SELECT_THREAD'
};
