module.exports = {
	CHANGE_CANCER_TYPE: 'CHANGE_CANCER_TYPE',
	CHANGE_CANCER_STAGE: 'CHANGE_CANCER_STAGE',
	CHANGE_GENETIC_VALUE: 'CHANGE_GENETIC_VALUE',
	CHANGE_GENETIC_TYPE: 'CHANGE_GENETIC_TYPE',
	CHANGE_DIAGNOSIS_DATE: 'CHANGE_DIAGNOSIS_DATE',
	CHANGE_PCPNAME: 'CHANGE_PCPNAME',
	CHANGE_PCPPHONE: 'CHANGE_PCPPHONE',
	CHANGE_PCPEMAIL: 'CHANGE_PCPEMAIL',
	SUBMIT_FORM: 'SUBMIT_FORM',
	CANCEL_FORM: 'CANCEL_FORM',

	SELECT_SURGERY: 'SELECT_SURGERY',
	CHANGE_SURGERY_TYPE: 'CHANGE_SURGERY_TYPE',
	CHANGE_SURGERY_LOCATION: 'CHANGE_SURGERY_LOCATION'
};