module.exports = {
	CHANGE_SELECTOR: 'CHANGE_SELECTOR',
	CHANGE_VALUE: 'CHANGE_VALUE',
	CHANGE_DIAGNOSIS_DATE: 'CHANGE_DIAGNOSIS_DATE',
	CHANGE_PCPNAME: 'CHANGE_PCPNAME',
	CHANGE_PCPPHONE: 'CHANGE_PCPPHONE',
	CHANGE_PCPEMAIL: 'CHANGE_PCPEMAIL',
	SUBMIT_FORM: 'SUBMIT_FORM',
	CANCEL_FORM: 'CANCEL_FORM'
};